### PR TITLE
 Add top-right and bottom-left bounds for offline map downloads

### PR DESCRIPTION
**Pull request by ekigamba**

### CODE REVIEW

**Comment by vincent-karuri** [comment]
Please add ui fields to specify top-right and bottom-left bounds for easier testing of this feature

**Comment by vincent-karuri** [comment]
Also merge master into this branch

**Comment by vincent-karuri** [comment]
Is there a way to visually confirm that this map is downloaded offline?

**Comment by ekigamba** [comment]
> Is there a way to visually confirm that this map is downloaded offline?

One of the new ways is to open the offline regions page and click on the *Navigate to map* on the offline region that you want to check.

**Pull request merged**
